# Generated by Django 5.1 on 2024-09-04 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/photo",
                verbose_name="Изображение",
            ),
        ),
    ]
