# Generated by Django 5.1 on 2024-09-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_created_at_alter_blog_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Просмотры"
            ),
        ),
    ]
