# Generated by Django 5.1 on 2024-09-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nuber_of_version",
                    models.PositiveIntegerField(verbose_name="номер версии"),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="название версии"),
                ),
                (
                    "is_actual",
                    models.BooleanField(
                        default=True, verbose_name="признак текущей версии"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ("product", "is_actual"),
            },
        ),
    ]
