# Generated by Django 5.1 on 2024-09-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="nuber_of_version",
            field=models.FloatField(verbose_name="номер версии"),
        ),
    ]
