# Generated by Django 5.1 on 2024-09-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_version_nuber_of_version"),
    ]

    operations = [
        migrations.RenameField(
            model_name="version",
            old_name="nuber_of_version",
            new_name="number_of_version",
        ),
    ]
