# Generated by Django 5.1 on 2024-09-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_rename_nuber_of_version_version_number_of_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_actual",
            field=models.BooleanField(
                default=False, verbose_name="признак текущей версии"
            ),
        ),
    ]
